//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCRealtorApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        public int Id { get; set; }
        public Nullable<double> Price { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public Nullable<int> Zip { get; set; }
        public Nullable<int> YearBuilt { get; set; }
        public Nullable<int> SquareFeet { get; set; }
        public Nullable<int> NumBedroom { get; set; }
        public Nullable<int> NumGarage { get; set; }
        public string RealtorName { get; set; }
        public string RealtorPhone { get; set; }
        public string RealtorEmail { get; set; }
        public Nullable<int> NumBathroom { get; set; }
        public string Property { get; set; }
    }
}
